#!/usr/bin/env bash

export CONTECO_LABEL="Conteco kibana base"
export CONTECO_DESCRIPTION="The ContEco Kibana base image."

export CONTECO_TYPE="kibana"
export CONTECO_NAME="base"
export CONTECO_TAG="6.6.2"

export CONTECO_BASE="external.kibana:6.6.2"
export CONTECO_BUILD="image-base"
