#!/usr/bin/env bash

export CONTECO_LABEL="kibana.base - ContEco"
export CONTECO_DESCRIPTION="ElasticSearch Kibana Base image, with minor configuration change."

export CONTECO_TYPE="kibana"
export CONTECO_NAME="base"
export CONTECO_TAG="7.1.1"

export CONTECO_BASE="external.kibana:7.1.1"
export CONTECO_BUILD="image-base"
