---
version: '3'
services:

# START SERVICE kibana.base
  kibana:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.kibana.base:7.1.1
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200', 'SERVER_BASEPATH=/${CONTECO_URLPREFIX}/kibana']
    command: []
    volumes: []
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: []
# END SERVICE kibana.base

volumes: {}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
