---
version: '3'
services:

# START SERVICE kibana.base
  kibana:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.kibana.base:7.9.2
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200','SERVER_BASEPATH=/${CONTECO_URLPREFIX}/kibana']
    command: []
    volumes: []
    ports: [5601:5601]
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTECO_DC_KIBANA_COMPOSE_EXTENSIONS}
# END SERVICE kibana.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
