---
version: '3'
services:

# START SERVICE kibana.base
  kibana:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.kibana.base:7.8.0
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200','SERVER_BASEPATH=/${CONTECO_URLPREFIX}/kibana']
    command: []
    volumes: []
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_KIBANA_DEPLOY_PLACEMENT_CONSTRAINTS}]
      ${CONTECO_DC_BASH_DEPLOY_EXTENSIONS}
    ${CONTECO_DC_BASH_SERVICE_EXTENSIONS}
# END SERVICE kibana.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${CONTECO_DC_BASH_GLOBAL_EXTENSIONS}
