---
version: '3'
services:

  ${CONTECO_DC_SERVICE_NAME}:
    image: ${CONTECO_DC_IMAGE_NAME}
    environment:
      ELASTICSEARCH_HOSTS: ${CONTECO_DC_ENV_ELASTICSEARCH_HOSTS}
      SERVER_BASEPATH: ${CONTECO_DC_ENV_SERVER_BASEPATH}
    volumes: [${CONTECO_DC_VOLUMES}]
    ports: [${CONTECO_DC_PORTS}]
    networks: [${CONTECO_DC_NETWORKS}]
    deploy:
      mode: ${CONTECO_DC_DEPLOY_MODE}
      resources:
        limits:
          memory: ${CONTECO_DC_DEPLOY_MEMORY_LIMIT}
        reservations:
          memory: ${CONTECO_DC_DEPLOY_MEMORY_RESERVATION}

networks:
  ${CONTECO_DC_NETWORKS}:
    external: true
