#!/usr/bin/env bash

# this file contains the default settings
# scaling parameters are applied after loading defaults

export CONTECO_DC_SERVICE_NAME="${CONTECO_TYPE}"
export CONTECO_DC_IMAGE_NAME="${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.${CONTECO_TYPE}.${CONTECO_NAME}:${CONTECO_TAG}"

export CONTECO_DC_ENV_ELASTICSEARCH_HOSTS="http://elasticsearch:9200"
export CONTECO_DC_ENV_SERVER_BASEPATH=""

export CONTECO_DC_DEPLOY_MODE="replicated"
export CONTECO_DC_DEPLOY_MEMORY_LIMIT="256m"
export CONTECO_DC_DEPLOY_MEMORY_RESERVATION="256m"

export CONTECO_DC_PORTS="5601:5601"

export CONTECO_DC_NETWORKS="${CONTECO_ECOSYSTEM}_overlay"
